language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - developers@launchkey.com
install:
  - pip install .
script: python setup.py test
